In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.linalg.det(a)

6.66133814775094e-16

In [4]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Act

In [5]:
A = np.array([[4,1,1,-5],[1,-7,2,-1],[3,0,4,-5],[1,2,0,-1]])
B = np.array([[0],[11],[6],[-5]])
d_A = np.linalg.det(A)
print(A,"\n\n",B)

[[ 4  1  1 -5]
 [ 1 -7  2 -1]
 [ 3  0  4 -5]
 [ 1  2  0 -1]] 

 [[ 0]
 [11]
 [ 6]
 [-5]]


In [6]:
np.linalg.solve(A,B)

array([[-7.73529412],
       [-2.05882353],
       [-1.26470588],
       [-6.85294118]])

In [7]:
A1 = np.array([[0,1,1,-5],[11,-7,2,-1],[6,0,4,-5],[-5,2,0,-1]])
A1

array([[ 0,  1,  1, -5],
       [11, -7,  2, -1],
       [ 6,  0,  4, -5],
       [-5,  2,  0, -1]])

In [8]:
np.linalg.det(A1)/np.linalg.det(A)

-7.735294117647062

In [9]:
A2 = np.array([[4,0,1,-5],[1,11,2,-1],[3,6,4,-5],[1,-5,0,-1]])
A2

array([[ 4,  0,  1, -5],
       [ 1, 11,  2, -1],
       [ 3,  6,  4, -5],
       [ 1, -5,  0, -1]])

In [10]:
np.linalg.det(A2)/np.linalg.det(A)

-2.058823529411766

In [11]:
A3 = np.array([[4,1,0,-5],[1,-7,11,-1],[3,0,6,-5],[1,2,-5,-1]])
A3

array([[ 4,  1,  0, -5],
       [ 1, -7, 11, -1],
       [ 3,  0,  6, -5],
       [ 1,  2, -5, -1]])

In [12]:
np.linalg.det(A3)/np.linalg.det(A)

-1.2647058823529418

In [13]:
A4 = np.array([[4,1,1,0],[1,-7,2,11],[3,0,4,6],[1,2,0,-5]])
A4

array([[ 4,  1,  1,  0],
       [ 1, -7,  2, 11],
       [ 3,  0,  4,  6],
       [ 1,  2,  0, -5]])

In [14]:
np.linalg.det(A4)/np.linalg.det(A)

-6.852941176470587

# 2

In [15]:
A1 = A
for i in range(4):
    A1[i,0] = B[i]
A1

array([[ 0,  1,  1, -5],
       [11, -7,  2, -1],
       [ 6,  0,  4, -5],
       [-5,  2,  0, -1]])

In [16]:
np.linalg.det(A1)/d_A

-7.735294117647062

In [17]:
A = np.array([[4,1,1,-5],[1,-7,2,-1],[3,0,4,-5],[1,2,0,-1]])
B = np.array([[0],[11],[6],[-5]])
d_A = np.linalg.det(A)

In [18]:
A2 = A
for i in range(4):
    A2[i,1] = B[i]
A2

array([[ 4,  0,  1, -5],
       [ 1, 11,  2, -1],
       [ 3,  6,  4, -5],
       [ 1, -5,  0, -1]])

In [19]:
np.linalg.det(A2)/d_A

-2.058823529411766

In [20]:
A = np.array([[4,1,1,-5],[1,-7,2,-1],[3,0,4,-5],[1,2,0,-1]])
B = np.array([[0],[11],[6],[-5]])
d_A = np.linalg.det(A)

In [21]:
A3 = A
for i in range(4):
    A3[i,2] = B[i]
A3

array([[ 4,  1,  0, -5],
       [ 1, -7, 11, -1],
       [ 3,  0,  6, -5],
       [ 1,  2, -5, -1]])

In [22]:
np.linalg.det(A3)/d_A

-1.2647058823529418

In [23]:
A = np.array([[4,1,1,-5],[1,-7,2,-1],[3,0,4,-5],[1,2,0,-1]])
B = np.array([[0],[11],[6],[-5]])
d_A = np.linalg.det(A)

In [24]:
A4 = A
for i in range(4):
    A4[i,3] = B[i]
A4

array([[ 4,  1,  1,  0],
       [ 1, -7,  2, 11],
       [ 3,  0,  4,  6],
       [ 1,  2,  0, -5]])

In [25]:
np.linalg.det(A4)/d_A

-6.852941176470587

# 3

In [26]:
A = np.array([[4,1,1,-5],[1,-7,2,-1],[3,0,4,-5],[1,2,0,-1]])
B = np.array([[0],[11],[6],[-5]])
d_A = np.linalg.det(A)

In [27]:
A1 = np.copy(A)
A2 = np.copy(A)
A3 = np.copy(A)
A4 = np.copy(A)
for i in range(4):
    A1[i,0] = B[i]
    A2[i,1] = B[i]
    A3[i,2] = B[i]
    A4[i,3] = B[i]
print(A,"\n\n",A1,"\n\n",A2,"\n\n",A3,"\n\n",A4)

[[ 4  1  1 -5]
 [ 1 -7  2 -1]
 [ 3  0  4 -5]
 [ 1  2  0 -1]] 

 [[ 0  1  1 -5]
 [11 -7  2 -1]
 [ 6  0  4 -5]
 [-5  2  0 -1]] 

 [[ 4  0  1 -5]
 [ 1 11  2 -1]
 [ 3  6  4 -5]
 [ 1 -5  0 -1]] 

 [[ 4  1  0 -5]
 [ 1 -7 11 -1]
 [ 3  0  6 -5]
 [ 1  2 -5 -1]] 

 [[ 4  1  1  0]
 [ 1 -7  2 11]
 [ 3  0  4  6]
 [ 1  2  0 -5]]


In [28]:
x1 = np.linalg.det(A1)/d_A
x2 = np.linalg.det(A2)/d_A
x3 = np.linalg.det(A3)/d_A
x4 = np.linalg.det(A4)/d_A
print(x1," ",x2," ",x3," ",x4)

-7.735294117647062   -2.058823529411766   -1.2647058823529418   -6.852941176470587


In [29]:
X = np.array([[x1],[x2],[x3],[x4]])
X

array([[-7.73529412],
       [-2.05882353],
       [-1.26470588],
       [-6.85294118]])

In [30]:
print(B)

[[ 0]
 [11]
 [ 6]
 [-5]]


In [31]:
np.matmul(A,X)

array([[-2.13162821e-14],
       [ 1.10000000e+01],
       [ 6.00000000e+00],
       [-5.00000000e+00]])

In [32]:
A@X

array([[-2.13162821e-14],
       [ 1.10000000e+01],
       [ 6.00000000e+00],
       [-5.00000000e+00]])

In [33]:
np.linalg.solve(A,B)

array([[-7.73529412],
       [-2.05882353],
       [-1.26470588],
       [-6.85294118]])