In [1]:
import numpy as np

# TEST

In [2]:
A = np.array([[1,1],[5,-3]])
B = np.array([[1],[4]])

In [3]:
x = np.linalg.solve(A,B)

In [4]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1])

X =  [0.875] ,Y =  [0.125]


# Ex

In [5]:
A = np.array([[1,2],[3,4]])

In [6]:
A

array([[1, 2],
       [3, 4]])

In [7]:
B = np.array([[1,2],[3,4]])

In [8]:
B

array([[1, 2],
       [3, 4]])

In [9]:
np.matmul(A,B)

array([[ 7, 10],
       [15, 22]])

# 1

In [10]:
A = np.array([[3,1],[2,-1]])
B = np.array([[4],[3]])
print(A,"\n",B)

[[ 3  1]
 [ 2 -1]] 
 [[4]
 [3]]


In [11]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1])

X =  [1.4] ,Y =  [-0.2]


# 2

In [12]:
A = np.array([[-1,3],[1,-5]])
B = np.array([[2],[-5]])
print(A,"\n",B)

[[-1  3]
 [ 1 -5]] 
 [[ 2]
 [-5]]


In [13]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1])

X =  [2.5] ,Y =  [1.5]


# 3

In [14]:
A = np.array([[1,3,-4],[1,-1,-2],[2,5,1]])
B = np.array([[2],[-5],[5]])
print(A,"\n",B)

[[ 1  3 -4]
 [ 1 -1 -2]
 [ 2  5  1]] 
 [[ 2]
 [-5]
 [ 5]]


In [15]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1],",Z = ",x[2])

X =  [-2.44117647] ,Y =  [1.91176471] ,Z =  [0.32352941]


# 4

In [16]:
A = np.array([[2,2,4],[-1,4,-2],[5,6,3]])
B = np.array([[6],[-3],[1]])
print(A,"\n",B)

[[ 2  2  4]
 [-1  4 -2]
 [ 5  6  3]] 
 [[ 6]
 [-3]
 [ 1]]


In [17]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1],",Z = ",x[2])

X =  [-1.] ,Y =  [0.] ,Z =  [2.]


# 5

In [18]:
A = np.array([[-3,6,3],[1,3,2],[2,-5,1]])
B = np.array([[7],[6],[-4]])
print(A,"\n",B)

[[-3  6  3]
 [ 1  3  2]
 [ 2 -5  1]] 
 [[ 7]
 [ 6]
 [-4]]


In [19]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1],",Z = ",x[2])

X =  [0.87037037] ,Y =  [1.27777778] ,Z =  [0.64814815]


# 6

In [20]:
A = np.array([[-1,6,5,1],[1,1,1,-1],[2,-4,3,2],[3,-1,1,3]])
B = np.array([[7],[6],[-4],[8]])
print(A,"\n",B)

[[-1  6  5  1]
 [ 1  1  1 -1]
 [ 2 -4  3  2]
 [ 3 -1  1  3]] 
 [[ 7]
 [ 6]
 [-4]
 [ 8]]


In [21]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1],",Z = ",x[2],",W = ",x[3])

X =  [3.94495413] ,Y =  [2.37614679] ,Z =  [-0.60550459] ,W =  [-0.28440367]


# 7

In [22]:
A = np.array([[4,2,3,2],[1,2,-1,-1],[1,-1,3,2],[3,1,-2,1]])
B = np.array([[8],[5],[3],[7]])
print(A,"\n",B)

[[ 4  2  3  2]
 [ 1  2 -1 -1]
 [ 1 -1  3  2]
 [ 3  1 -2  1]] 
 [[8]
 [5]
 [3]
 [7]]


In [23]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1],",Z = ",x[2],",W = ",x[3])

X =  [31.] ,Y =  [-29.33333333] ,Z =  [8.] ,W =  [-40.66666667]


# 8

In [24]:
A = np.array([[1,2,-3,-1],[3,1,3,1],[-1,3,1,3],[5,6,5,-4]])
B = np.array([[-5],[3],[2],[-6]])
print(A,"\n",B)

[[ 1  2 -3 -1]
 [ 3  1  3  1]
 [-1  3  1  3]
 [ 5  6  5 -4]] 
 [[-5]
 [ 3]
 [ 2]
 [-6]]


In [25]:
x = np.linalg.solve(A,B)
print("X = ",x[0],",Y = ",x[1],",Z = ",x[2],",W = ",x[3])

X =  [0.12559242] ,Y =  [-0.83412322] ,Z =  [0.71800948] ,W =  [1.30331754]


# 9

In [26]:
A = np.array([[1,2,-3,-4,3],[3,1,-4,1,4],[1,9,1,5,8],[2,-1,-2,1,1],[4,0,5,7,-1]])
B = np.array([[5],[7],[6],[9],[4]])
print(A,"\n",B)

[[ 1  2 -3 -4  3]
 [ 3  1 -4  1  4]
 [ 1  9  1  5  8]
 [ 2 -1 -2  1  1]
 [ 4  0  5  7 -1]] 
 [[5]
 [7]
 [6]
 [9]
 [4]]


In [27]:
x = np.linalg.solve(A,B)
print("X1 = ",x[0],",X2 = ",x[1],",X3 = ",x[2],",X4 = ",x[3],",X5 = ",x[4])

X1 =  [-13.63414634] ,X2 =  [-63.51219512] ,X3 =  [45.29268293] ,X4 =  [-13.07317073] ,X5 =  [76.41463415]


# 10

In [28]:
A = np.array([[1,3,0,4,-3],[3,2,-4,0,2],[-1,3,2,3,2],[2,-1,-2,4,3],[1,-1,5,2,-3]])
B = np.array([[4],[2],[3],[6],[10]])
print(A,"\n",B)

[[ 1  3  0  4 -3]
 [ 3  2 -4  0  2]
 [-1  3  2  3  2]
 [ 2 -1 -2  4  3]
 [ 1 -1  5  2 -3]] 
 [[ 4]
 [ 2]
 [ 3]
 [ 6]
 [10]]


In [29]:
x = np.linalg.solve(A,B)
print("X1 = ",x[0],",X2 = ",x[1],",X3 = ",x[2],",X4 = ",x[3],",X5 = ",x[4])

X1 =  [2.3910522] ,X2 =  [-0.10107705] ,X3 =  [1.41176471] ,X4 =  [0.73156587] ,X5 =  [0.33802817]


# End