In [1]:
import numpy as np

# EX

In [21]:
A = np.array([[1],[2]])
B = np.array([[1,2,6],[2,3,-3],[-1,0,-5]])
print(A@B)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

# Act1

In [3]:
A = np.array([[-2,2,0],[6,-1,3],[7,1,1]])
B = np.array([[1,2,6],[2,3,-3],[-1,0,-5]])
C = np.array([[2,-5,2],[-1,4,3],[0,6,1]])

In [4]:
print("A = ","\n",A,"\n","B = ","\n",B,"\n","C = ","\n",C)

A =  
 [[-2  2  0]
 [ 6 -1  3]
 [ 7  1  1]] 
 B =  
 [[ 1  2  6]
 [ 2  3 -3]
 [-1  0 -5]] 
 C =  
 [[ 2 -5  2]
 [-1  4  3]
 [ 0  6  1]]


# 1.1

In [5]:
# A * B
print(A@B)

[[  2   2 -18]
 [  1   9  24]
 [  8  17  34]]


# 1.2

In [6]:
# B * A
print(B@A)

[[ 52   6  12]
 [ -7  -2   6]
 [-33  -7  -5]]


# 1.3

In [7]:
# A * B**-1
print(A@np.linalg.inv(B))

[[ 1.93103448 -0.62068966  2.68965517]
 [-3.24137931  1.82758621 -5.5862069 ]
 [-3.06896552  2.37931034 -5.31034483]]


# 1.4

In [8]:
# C * A * B
print(C@A@B)

[[ 15  -7 -88]
 [ 26  85 216]
 [ 14  71 178]]


# 1.5

In [9]:
# B**-1 * C**-1
print(np.linalg.inv(B)@np.linalg.inv(C))

[[-0.2789272  -0.04061303 -0.14789272]
 [ 0.20766284 -0.03295019  0.20076628]
 [ 0.02911877 -0.04521073  0.04291188]]


# 1.6

In [10]:
# C * B**-1 * A
print(C@np.linalg.inv(B)@A)

[[-21.75862069 -10.82758621  -3.17241379]
 [ 11.82758621   8.44827586   1.55172414]
 [ 16.72413793   8.51724138   3.48275862]]


# 1.7

In [11]:
# A**-1 * B**-1 * C**-1
print(np.linalg.inv(A)@np.linalg.inv(B)@np.linalg.inv(C))

[[ 0.02302884 -0.00112926  0.01177657]
 [-0.11643477 -0.02143577 -0.06216979]
 [-0.01564832 -0.01587014  0.02264569]]


# 1.8

In [12]:
# (A * B *C)**-1
print(np.linalg.inv(A@B@C))

[[-0.10846945 -0.1866102   0.08933253]
 [-0.01318814 -0.00391208  0.00100827]
 [ 0.0292196   0.00713854  0.00846945]]


# 1.9

In [13]:
# (C * A)**-1 * B
print(np.linalg.inv(C@A)@B)

[[ 0.23157895  0.23157895  0.05263158]
 [-0.24619883 -0.02397661  0.2748538 ]
 [-0.64152047 -0.53040936 -0.30994152]]


# 1.10

In [14]:
# B**-1 * A * C * A**-1
print(np.linalg.inv(B)@A@C@np.linalg.inv(A))

[[-1.38656987 -5.10707804  3.52813067]
 [ 1.02450091  4.52087114 -2.94192377]
 [ 1.29310345 -0.62068966  0.62068966]]


# Act2

In [15]:
A = np.array([[3,2,4,1,5],[4,-3,8,2,-1],[-1,-4,2,-9,2],[5,7,-1,4,3],[2,4,7,1,-6]])
B = np.array([[16],[8],[-16],[10],[9]])
print(A,"\n",B)

[[ 3  2  4  1  5]
 [ 4 -3  8  2 -1]
 [-1 -4  2 -9  2]
 [ 5  7 -1  4  3]
 [ 2  4  7  1 -6]] 
 [[ 16]
 [  8]
 [-16]
 [ 10]
 [  9]]


In [16]:
x = np.linalg.solve(A,B)
print("X1 = ",x[0],",X2 = ",x[1],",X3 = ",x[2],",X4 = ",x[3],",X5 = ",x[4])

X1 =  [-2.36788381] ,X2 =  [1.37435838] ,X3 =  [2.33288614] ,X4 =  [2.33463602] ,X5 =  [1.73775082]


# Act3

In [17]:
A = np.array([[3,8,4,3,0,1],[1,-3,1,7,-5,3],[-2,6,1,-3,2,-4],[1,3,0,-4,3,-8],[0,4,2,5,3,3],[6,3,1,-1,2,6]])
B = np.array([[12],[4],[8],[-3],[16],[9]])
print(A,"\n",B)

[[ 3  8  4  3  0  1]
 [ 1 -3  1  7 -5  3]
 [-2  6  1 -3  2 -4]
 [ 1  3  0 -4  3 -8]
 [ 0  4  2  5  3  3]
 [ 6  3  1 -1  2  6]] 
 [[12]
 [ 4]
 [ 8]
 [-3]
 [16]
 [ 9]]


In [18]:
x = np.linalg.solve(A,B)
print("X1 = ",x[0],",X2 = ",x[1],",X3 = ",x[2],",X4 = ",x[3],",X5 = ",x[4],",X6 = ",x[5])

X1 =  [1.51027703] ,X2 =  [8.55555556] ,X3 =  [-19.12511171] ,X4 =  [5.0238308] ,X5 =  [-2.15072982] ,X6 =  [0.45367888]


# Act4

In [19]:
A = np.array([[3,7,4,8,0,-1,1],[-1,3,0,-6,-5,3,-1],[5,-6,3,-3,2,-4,1],[1,5,0,-4,-3,5,-3],[0,-5,2,5,3,3,2],[-6,4,-1,6,-7,6,-5],[4,-5,5,-3,2,-6,1]])
B = np.array([[9],[-4],[12],[3],[15],[-9],[10]])
print(A,"\n",B)

[[ 3  7  4  8  0 -1  1]
 [-1  3  0 -6 -5  3 -1]
 [ 5 -6  3 -3  2 -4  1]
 [ 1  5  0 -4 -3  5 -3]
 [ 0 -5  2  5  3  3  2]
 [-6  4 -1  6 -7  6 -5]
 [ 4 -5  5 -3  2 -6  1]] 
 [[ 9]
 [-4]
 [12]
 [ 3]
 [15]
 [-9]
 [10]]


In [20]:
x = np.linalg.solve(A,B)
print("X1 = ",x[0],",X2 = ",x[1],",X3 = ",x[2],",X4 = ",x[3],",X5 = ",x[4],",X6 = ",x[5],",X7 = ",x[6])

X1 =  [1.7607526] ,X2 =  [-0.60134443] ,X3 =  [1.7576948] ,X4 =  [0.28707865] ,X5 =  [0.65325799] ,X6 =  [1.57664628] ,X7 =  [0.1763911]


# END