In [1]:
import numpy as np

# Act1

In [2]:
A = np.array([[1,2,0,-2],[3,4,-5,1],[1,1,2,0],[2,1,0,-1]])
B = np.array([[-1,2,1,-2],[1,3,-5,1],[0,1,-2,2],[2,2,4,-1]])
C = np.array([[1,0,2,0],[-3,-4,5,1],[1,4,3,-1],[-2,-1,3,-2]])
print(A,"\n\n",B,"\n\n",C)

# 1.1

In [3]:
# B * C
print(B@C)
#np.matmul(B,C)

[[ -2  -2   5   5]
 [-15 -33   5   6]
 [ -9 -14   5  -1]
 [  2   9  23   0]]


# 1.2

In [4]:
# A**-1 * C
print(np.linalg.inv(A)@C)
#np.matmul(np.linalg.inv(A),C)

[[-1.66666667 -0.66666667  1.33333333 -1.33333333]
 [ 1.33333333  1.33333333  0.73333333  0.86666667]
 [ 0.66666667  1.66666667  0.46666667 -0.26666667]
 [ 0.          1.          0.4         0.2       ]]


# 1.3

In [5]:
# A * C**-1 * B
print(A@np.linalg.inv(C)@B)
#np.matmul(np.matmul(A,np.linalg.inv(C)),B)

[[ 0.27777778  0.44444444  6.05555556 -2.05555556]
 [-1.75925926 -3.81481481 -2.35185185  2.01851852]
 [-0.82407407  1.48148148 -0.56481481 -0.60185185]
 [-1.11111111  1.22222222  5.77777778 -3.77777778]]


# 1.4

In [6]:
# (B * C)**-1 * A
print(np.linalg.inv(B@C)@A)

[[ 0.12326389 -0.07638889 -1.59895833  0.67013889]
 [-0.11352238 -0.02276235  0.82783565 -0.38869599]
 [ 0.12065972  0.05902778 -0.18489583  0.05034722]
 [ 0.08323688  0.30131173 -0.12355324 -0.33777006]]


# 1.5

In [7]:
# (B * C**-1)**-1 * (A * C)**-1
print(np.linalg.inv(B@np.linalg.inv(C))@np.linalg.inv(A@C))

[[ 0.18836806 -0.00850694  0.01909722 -0.20815972]
 [-0.58680556  0.06736111 -0.07638889  0.86597222]
 [ 0.046875   -0.034375   -0.05208333  0.26770833]
 [-0.41695602  0.01811343 -0.13136574  0.6541088 ]]


# 1.6

In [8]:
# (A * B**-1 * C * A)**-1
print(np.linalg.inv(A@np.linalg.inv(B)@C@A))

[[-0.71193416  0.35390947 -0.64609053  0.16049383]
 [ 0.64320988 -0.23691358  0.51975309 -0.26592593]
 [ 0.17325103 -0.00572016  0.0909465  -0.13061728]
 [-0.26831276  0.07893004  0.08559671  0.14765432]]


# Act2

In [9]:
A = np.array([[5.3,0.8,1.4],[6.8,-2.5,3.4],[-1.8,3.9,-5.7]])
B = np.array([[4.5],[5.4],[-8.9]])
print(A,"\n\n",B)

[[ 5.3  0.8  1.4]
 [ 6.8 -2.5  3.4]
 [-1.8  3.9 -5.7]] 

 [[ 4.5]
 [ 5.4]
 [-8.9]]


In [10]:
x = np.linalg.solve(A,B)
print("x1 = ",x[0]," x2 = ",x[1]," x3 = ",x[2])

x1 =  [0.0515381]  x2 =  [1.17394311]  x3 =  [2.34835255]


# Act3

In [17]:
A = np.array([[2.6,4.7,-3.1,1.2],[0.4,0.5,2.4,-3.6],[1.6,-3.7,1.4,-0.9],[-2.9,1.3,-2.4,1.8]])
B = np.array([[6.5],[4.8],[5.3],[-2.9]])
print(A,"\n\n",B)

[[ 2.6  4.7 -3.1  1.2]
 [ 0.4  0.5  2.4 -3.6]
 [ 1.6 -3.7  1.4 -0.9]
 [-2.9  1.3 -2.4  1.8]] 

 [[ 6.5]
 [ 4.8]
 [ 5.3]
 [-2.9]]


In [18]:
x = np.linalg.solve(A,B)
print("x1 = ",x[0]," x2 = ",x[1]," x3 = ",x[2]," x4 = ",x[3])

x1 =  [1.50770845]  x2 =  [-1.51127613]  x3 =  [-4.92774235]  x4 =  [-4.6608712]


# Act4

In [13]:
A = np.array([[3.6,4.7,0,-1.8,2.7],[4.4,0,2.4,-3.6,1.2],[0.6,-5.2,1.4,0,-4.5],[0,1.6,-2.4,1.8,-2.4],[-2.8,3.7,5.4,-0.9,3.7]])
B = np.array([[5.2],[4.3],[-3.8],[1.5],[7.2]])
print(A,"\n\n",B)

[[ 3.6  4.7  0.  -1.8  2.7]
 [ 4.4  0.   2.4 -3.6  1.2]
 [ 0.6 -5.2  1.4  0.  -4.5]
 [ 0.   1.6 -2.4  1.8 -2.4]
 [-2.8  3.7  5.4 -0.9  3.7]] 

 [[ 5.2]
 [ 4.3]
 [-3.8]
 [ 1.5]
 [ 7.2]]


In [14]:
x = np.linalg.solve(A,B)
print("x1 = ",x[0]," x2 = ",x[1]," x3 = ",x[2]," x4 = ",x[3]," x5 = ",x[4])

x1 =  [-2.88202092]  x2 =  [2.44013242]  x3 =  [-1.04492823]  x4 =  [-6.30840739]  x5 =  [-2.68462237]


# End