In [1]:
import numpy as np

# ex

In [55]:
u = np.array([1,2,3])
v = np.array([5,6,2])
print(u,v)

[1 2 3] [5 6 2]


In [56]:
v_norm = np.sqrt(sum(v**2))

In [57]:
proj_of_u_on_v = (np.dot(u,v)/v_norm**2)*v

In [58]:
print("projection of vector u on verter v is : ",proj_of_u_on_v)

projection of vector u on verter v is :  [1.76923077 2.12307692 0.70769231]


# ex

In [6]:
def projectuv(u,v) :
    v_norm = np.sqrt(sum(v**2))
    proj_of_u_on_v = (np.dot(u,v)/v_norm**2)*v
    return proj_of_u_on_v

In [7]:
v1 = np.array([1,2,3])
v2 = np.array([0,6,2])
v3 = np.array([-1,3,2])

In [8]:
u1 = v1
print(u1)

[1 2 3]


In [9]:
u2 = v2 - projectuv(v2,u1)
print(u2)

[-1.28571429  3.42857143 -1.85714286]


In [10]:
u3 = v3 - projectuv(v3,u1) - projectuv(v3,u2)
print(u3)

[-1.18644068 -0.16949153  0.50847458]


# act

In [46]:
a = np.array([1,2,3])
b = np.array([0,-2,3])
print(a,b)

[1 2 3] [ 0 -2  3]


In [47]:
b_norm = np.sqrt(sum(b**2))
proj_of_a_on_b = (np.dot(a,b)/b_norm**2)*b

In [48]:
print("projection of vector a on verter b is : ",proj_of_a_on_b)

projection of vector a on verter b is :  [ 0.         -0.76923077  1.15384615]


In [14]:
a = np.array([-3,0,7])
b = np.array([1,8,-6])
print(a,b)
b_norm = np.sqrt(sum(b**2))
proj_of_a_on_b = (np.dot(a,b)/b_norm**2)*b
print("projection of vector a on verter b is : ",proj_of_a_on_b)

[-3  0  7] [ 1  8 -6]
projection of vector a on verter b is :  [-0.44554455 -3.56435644  2.67326733]


In [15]:
a = np.array([10,-2,4])
b = np.array([5,1,2])
print(a,b)
b_norm = np.sqrt(sum(b**2))
proj_of_a_on_b = (np.dot(a,b)/b_norm**2)*b
print("projection of vector a on verter b is : ",proj_of_a_on_b)

[10 -2  4] [5 1 2]
projection of vector a on verter b is :  [9.33333333 1.86666667 3.73333333]


In [16]:
a = np.array([-4,-5,8,3])
b = np.array([-1,2,6,1])
print(a,b)
b_norm = np.sqrt(sum(b**2))
proj_of_a_on_b = (np.dot(a,b)/b_norm**2)*b
print("projection of vector a on verter b is : ",proj_of_a_on_b)

[-4 -5  8  3] [-1  2  6  1]
projection of vector a on verter b is :  [-1.07142857  2.14285714  6.42857143  1.07142857]


In [17]:
a = np.array([8,4,-2,-5])
b = np.array([3,-1,0,6])
print(a,b)
b_norm = np.sqrt(sum(b**2))
proj_of_a_on_b = (np.dot(a,b)/b_norm**2)*b
print("projection of vector a on verter b is : ",proj_of_a_on_b)

[ 8  4 -2 -5] [ 3 -1  0  6]
projection of vector a on verter b is :  [-0.65217391  0.2173913  -0.         -1.30434783]


# act

In [18]:
v1 = np.array([2,3,-3])
v2 = np.array([1,-2,1])
v3 = np.array([0,2,1])

In [19]:
u1 = v1
print(u1)

[ 2  3 -3]


In [20]:
u2 = v2 - projectuv(v2,u1)
print(u2)

[ 1.63636364 -1.04545455  0.04545455]


In [21]:
u3 = v3 - projectuv(v3,u1) - projectuv(v3,u2)
print(u3)

[0.61445783 1.02409639 1.43373494]


In [22]:
v1 = np.array([2,2,1])
v2 = np.array([0,-3,2])
v3 = np.array([1,3,4])

In [23]:
u1 = v1
print(u1)

[2 2 1]


In [24]:
u2 = v2 - projectuv(v2,u1)
print(u2)

[ 0.88888889 -2.11111111  2.44444444]


In [25]:
u3 = v3 - projectuv(v3,u1) - projectuv(v3,u2)
print(u3)

[-2.00990099  1.14851485  1.72277228]


In [26]:
v1 = np.array([-1,5,4])
v2 = np.array([-1,-2,3])
v3 = np.array([-2,2,-4])

In [27]:
u1 = v1
print(u1)

[-1  5  4]


In [28]:
u2 = v2 - projectuv(v2,u1)
print(u2)

[-0.92857143 -2.35714286  2.71428571]


In [29]:
u3 = v3 - projectuv(v3,u1) - projectuv(v3,u2)
print(u3)

[-3.01899827  0.13126079 -0.91882556]


In [30]:
v1 = np.array([1,3,6,5])
v2 = np.array([2,-7,2,0])
v3 = np.array([3,2,0,-5])

In [31]:
u1 = v1
print(u1)

[1 3 6 5]


In [32]:
u2 = v2 - projectuv(v2,u1)
print(u2)

[ 2.09859155 -6.70422535  2.5915493   0.49295775]


In [33]:
u3 = v3 - projectuv(v3,u1) - projectuv(v3,u2)
print(u3)

[ 3.58229115  1.53576788  1.79289645 -3.7893947 ]


In [34]:
v1 = np.array([-2,4,0,2])
v2 = np.array([3,-5,1,1])
v3 = np.array([2,1,-5,3])

In [35]:
u1 = v1
print(u1)

[-2  4  0  2]


In [36]:
u2 = v2 - projectuv(v2,u1)
print(u2)

[ 1. -1.  1.  3.]


In [37]:
u3 = v3 - projectuv(v3,u1) - projectuv(v3,u2)
print(u3)

[ 2.08333333  0.41666667 -5.41666667  1.25      ]


# end