# Example

In [1]:
import numpy as np

In [28]:
A = np.array([[3,2,1],[4,1,1],[-1,1,3]])
print(A)

[[ 3  2  1]
 [ 4  1  1]
 [-1  1  3]]


In [3]:
n = 3
I = np.identity(n)
M = np.concatenate( (A,I) , axis = 1)
for i in range(0,n):
    pivot = M[i][i]
    row = M[i]
    M[i] = row/pivot
    for j in [k for k in range(0,n) if k!=i]:
        M[j] = M[j] - M[i] * M[j][i]
    inverse = M[:,n:]
print(inverse)

[[-0.13333333  0.33333333 -0.06666667]
 [ 0.86666667 -0.66666667 -0.06666667]
 [-0.33333333  0.33333333  0.33333333]]


In [4]:
print(np.linalg.inv(A))

[[-0.13333333  0.33333333 -0.06666667]
 [ 0.86666667 -0.66666667 -0.06666667]
 [-0.33333333  0.33333333  0.33333333]]


# 1.1

In [5]:
A = np.array([[3,4],[0,2]])
print(A)

[[3 4]
 [0 2]]


In [6]:
print(np.linalg.inv(A))

[[ 0.33333333 -0.66666667]
 [ 0.          0.5       ]]


# 1.2

In [7]:
A = np.array([[-3,0.6],[-1,3]])
print(A)

[[-3.   0.6]
 [-1.   3. ]]


In [8]:
print(np.linalg.inv(A))

[[-0.35714286  0.07142857]
 [-0.11904762  0.35714286]]


# 1.3

In [9]:
A = np.array([[2,0],[8,-2]])
print(A)

[[ 2  0]
 [ 8 -2]]


In [10]:
print(np.linalg.inv(A))

[[ 0.5  0. ]
 [ 2.  -0.5]]


# 1.4

In [11]:
A = np.array([[3,-1,2],[0,1,4],[0,0,5]])
print(A)

[[ 3 -1  2]
 [ 0  1  4]
 [ 0  0  5]]


In [12]:
print(np.linalg.inv(A))

[[ 0.33333333  0.33333333 -0.4       ]
 [ 0.          1.         -0.8       ]
 [ 0.          0.          0.2       ]]


# 1.5

In [13]:
A = np.array([[3,0,2],[-5,1,0],[2,-10,5]])
print(A)

[[  3   0   2]
 [ -5   1   0]
 [  2 -10   5]]


In [14]:
print(np.linalg.inv(A))

[[ 0.04504505 -0.18018018 -0.01801802]
 [ 0.22522523  0.0990991  -0.09009009]
 [ 0.43243243  0.27027027  0.02702703]]


# 1.6

In [15]:
A = np.array([[6,0,8],[0,15,-8],[2,-12,5]])
print(A)

[[  6   0   8]
 [  0  15  -8]
 [  2 -12   5]]


In [16]:
print(np.linalg.inv(A))

[[ 0.05737705  0.26229508  0.32786885]
 [ 0.04371585 -0.03825137 -0.13114754]
 [ 0.08196721 -0.19672131 -0.24590164]]


# 1.7

In [17]:
A = np.array([[3,2,4,1],[2,1,-5,0],[10,4,-2,8],[0,1,4,5]])
print(A)

[[ 3  2  4  1]
 [ 2  1 -5  0]
 [10  4 -2  8]
 [ 0  1  4  5]]


In [18]:
print(np.linalg.inv(A))

[[-0.05487805 -0.34756098  0.18597561 -0.28658537]
 [ 0.50609756  0.87195122 -0.32621951  0.42073171]
 [ 0.07926829 -0.16463415  0.00914634 -0.0304878 ]
 [-0.16463415 -0.04268293  0.05792683  0.1402439 ]]


# 1.8

In [19]:
A = np.array([[-1,0,2,6],[2,3,5,4],[8,1,-2,0],[3,8,9,7]])
print(A)

[[-1  0  2  6]
 [ 2  3  5  4]
 [ 8  1 -2  0]
 [ 3  8  9  7]]


In [20]:
print(np.linalg.inv(A))

[[-0.04042179  0.23901582  0.09841828 -0.10193322]
 [ 0.00702988 -0.65026362  0.02636204  0.3655536 ]
 [-0.15817223  0.63093146 -0.09314587 -0.22495606]
 [ 0.21265378 -0.17047452  0.04745167  0.05799649]]


# 1.9

In [21]:
A = np.array([[8,3,1,8,7],[4,7,2,1,5],[1,8,1,0,4],[0,7,2,3,6],[2,9,2,7,3]])
print(A)

[[8 3 1 8 7]
 [4 7 2 1 5]
 [1 8 1 0 4]
 [0 7 2 3 6]
 [2 9 2 7 3]]


In [22]:
print(np.linalg.inv(A))

[[ 0.04433078  0.157289    0.00170503 -0.18755328  0.00724638]
 [-0.01278772 -0.05498721  0.19181586 -0.09974425  0.06521739]
 [-0.27621483  0.71227621 -0.85677749  0.2455243   0.10869565]
 [ 0.04688832 -0.13171355 -0.03665814  0.03239557  0.0942029 ]
 [ 0.08354646 -0.10741688  0.0801364   0.18499574 -0.15942029]]


# 1.10

In [23]:
A = np.array([[-5,3,3,7,5],[4,2,0,1,-5],[-2,8,3,2,4],[3,5,1,8,8],[7,0,2,-2,2]])
print(A)

[[-5  3  3  7  5]
 [ 4  2  0  1 -5]
 [-2  8  3  2  4]
 [ 3  5  1  8  8]
 [ 7  0  2 -2  2]]


In [24]:
print(np.linalg.inv(A))

[[-0.03157895  0.04561404 -0.02807018  0.04561404  0.06666667]
 [-0.1         0.03333333  0.13333333  0.03333333 -0.06666667]
 [ 0.24817814  0.06032389 -0.00161943 -0.17044534  0.21538462]
 [ 0.09048583  0.08724696 -0.08623482  0.04878543 -0.03076923]
 [-0.04716599 -0.13272605  0.01363023  0.05958165  0.02051282]]


# End