In [1]:
import numpy as np
from numpy.linalg import eig

# Ex

In [2]:
a = np.array([[0,2],[2,3]])
a

array([[0, 2],
       [2, 3]])

In [3]:
w,v = eig(a)
print('E-value',w)
print('E-vector',v)

E-value [-1.  4.]
E-vector [[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]


# Act

In [4]:
A = np.array([[5,-1,2],[1,3,0],[2,-8,2]])
B = np.array([[3,1,6],[-1,1,5],[-2,5,4]])
print(A,'\n\n',B)

[[ 5 -1  2]
 [ 1  3  0]
 [ 2 -8  2]] 

 [[ 3  1  6]
 [-1  1  5]
 [-2  5  4]]


In [5]:
w,v = eig(A)
print('E-value',w)
print('E-vector',v)

E-value [0.15086295+0.j         4.92456852+1.50424564j 4.92456852-1.50424564j]
E-vector [[ 0.3561561 +0.j          0.79686292+0.j          0.79686292-0.j        ]
 [-0.1250049 +0.j          0.25702858-0.20089392j  0.25702858+0.20089392j]
 [-0.92602732+0.j          0.09846002+0.49889183j  0.09846002-0.49889183j]]


In [6]:
w,v = eig(A@B)
print('E-value',w)
print('E-vector',v)

E-value [-28.49926118  23.9902697    0.50899148]
E-vector [[ 0.44489985 -0.93952576  0.59008953]
 [ 0.48605302 -0.24805887 -0.79640835]
 [-0.75220781 -0.23613161  0.13239373]]


In [7]:
w,v = eig(np.linalg.inv(A))
print('E-value',w)
print('E-vector',v)

E-value [6.62853252+0.j         0.18573374+0.05673374j 0.18573374-0.05673374j]
E-vector [[-0.3561561 +0.j          0.79686292+0.j          0.79686292-0.j        ]
 [ 0.1250049 +0.j          0.25702858+0.20089392j  0.25702858-0.20089392j]
 [ 0.92602732+0.j          0.09846002-0.49889183j  0.09846002+0.49889183j]]


In [8]:
w,v = eig(B@A)
print('E-value',w)
print('E-vector',v)

E-value [ 23.9902697  -28.49926118   0.50899148]
E-vector [[ 0.99182317 -0.55847928 -0.35284825]
 [ 0.10821884 -0.77158166  0.14457957]
 [ 0.06764226 -0.3045696   0.924443  ]]


In [9]:
w,v = eig(np.linalg.inv(A@B))
print('E-value',w)
print('E-vector',v)

E-value [ 1.96466943  0.04168357 -0.03508863]
E-vector [[-0.59008953  0.93952576 -0.44489985]
 [ 0.79640835  0.24805887 -0.48605302]
 [-0.13239373  0.23613161  0.75220781]]


# Act

In [10]:
C = np.array([[1,0,7,-8],[1,2,2,-5],[2,0,8,7],[7,-1,5,6]])
D = np.array([[2,0,-7,8],[-3,2,3,-5],[0,4,3,1],[7,-1,2,-6]])
print(C,'\n\n',D)

[[ 1  0  7 -8]
 [ 1  2  2 -5]
 [ 2  0  8  7]
 [ 7 -1  5  6]] 

 [[ 2  0 -7  8]
 [-3  2  3 -5]
 [ 0  4  3  1]
 [ 7 -1  2 -6]]


In [11]:
w,v = eig(C@D)
print('E-value',w)
print('E-vector',v)

E-value [-79.96551076   9.51054105  52.55587186  34.89909785]
E-vector [[ 0.62014471  0.21101495  0.46561537  0.36785521]
 [ 0.37420138 -0.47845375  0.06956904 -0.04962051]
 [-0.49008908  0.6845681   0.44483918  0.73248632]
 [-0.48498098  0.50785945  0.76189277  0.57068742]]


In [12]:
w,v = eig(D@C)
print('E-value',w)
print('E-vector',v)

E-value [-79.96551076  52.55587186   9.51054105  34.89909785]
E-vector [[ 0.13252761  0.66018812 -0.13873781 -0.0535578 ]
 [-0.02636826 -0.62984151 -0.93775189  0.57278051]
 [-0.07680318  0.40070041  0.29265928 -0.7918365 ]
 [ 0.98784737 -0.08300904  0.12539439 -0.20505855]]


In [13]:
w,v = eig(C@C)
print('E-value',w)
print('E-vector',v)

E-value [181.29722901+0.j           5.50006316+0.j
 -42.89864608+7.82699212j -42.89864608-7.82699212j]
E-vector [[ 0.05852316+0.j          0.16940557+0.j         -0.73155059+0.j
  -0.73155059-0.j        ]
 [-0.11865042+0.j          0.98470963+0.j         -0.33403282+0.23580247j
  -0.33403282-0.23580247j]
 [ 0.78936016+0.j         -0.01183462+0.j          0.22530436-0.20162858j
   0.22530436+0.20162858j]
 [ 0.59950618+0.j         -0.03884129+0.j          0.16011172+0.42497189j
   0.16011172-0.42497189j]]


In [14]:
w,v = eig(np.linalg.inv(C)@np.linalg.inv(D))
print('E-value',w)
print('E-vector',v)

E-value [ 0.10514649 -0.01250539  0.01902737  0.02865404]
E-vector [[-0.13873781 -0.13252761 -0.66018812 -0.0535578 ]
 [-0.93775189  0.02636826  0.62984151  0.57278051]
 [ 0.29265928  0.07680318 -0.40070041 -0.7918365 ]
 [ 0.12539439 -0.98784737  0.08300904 -0.20505855]]


In [15]:
w,v = eig(np.linalg.inv(D@D))
print('E-value',w)
print('E-vector',v)

E-value [-0.05540662+0.08724437j -0.05540662-0.08724437j  0.00786107+0.j
  0.01160562+0.j        ]
E-vector [[-0.21664553+0.28795393j -0.21664553-0.28795393j  0.54496078+0.j
   0.65115849+0.j        ]
 [ 0.34332938+0.41185589j  0.34332938-0.41185589j -0.2056771 +0.j
  -0.6106298 +0.j        ]
 [-0.6247755 +0.j         -0.6247755 -0.j          0.11398236+0.j
  -0.34207199+0.j        ]
 [-0.4349638 +0.05575815j -0.4349638 -0.05575815j -0.80481221+0.j
   0.29344611+0.j        ]]


# End